#!/usr/bin/env python3
"""
01_download.py — Download APS PS Gazette PDFs from APSC S3.

Probes the public APSC S3 bucket for gazette PDFs and downloads them to
data/pdfs/. Maintains data/manifest.csv to track what has been downloaded;
skips dates already recorded in the manifest (pass --no-skip to re-probe).

The APSC S3 bucket is public — no credentials required.

Usage:
    # Current year only (typical for incremental / CI runs):
    python pipeline/01_download.py

    # Full backfill:
    python pipeline/01_download.py --year-start 2021

    # Probe without downloading:
    python pipeline/01_download.py --year-start 2026 --probe-only
"""

import argparse
import csv
import math
import sys
import time
from datetime import date, timedelta
from pathlib import Path

import requests

BASE_URL = "https://s3-ap-southeast-2.amazonaws.com/apsc.gazette/"
EARLIEST_DATE = date(2020, 1, 1)

MANIFEST_PATH = Path("data/manifest.csv")
PDF_DIR = Path("data/pdfs")

MANIFEST_FIELDS = [
    "gazette_date", "gazette_id", "gazette_type",
    "filename", "url", "status",
]

def _ps_number(d: date) -> int:
    """PS gazette number for any weekday.

    Finds the Thursday of the same gazette week, then ceil(day_of_year / 7).
    Matches 01_gazette_download.R gazette_ps_n().
    """
    days_to_thursday = (3 - d.weekday()) % 7   # Monday=0, Thursday=3
    thursday = d + timedelta(days=days_to_thursday)
    return math.ceil(thursday.timetuple().tm_yday / 7)


def _encode(filename: str) -> str:
    """Encode filename for APSC S3 URL: spaces → +, all other chars literal."""
    return BASE_URL + filename.replace(" ", "+")


def _gazette_type(filename: str) -> str:
    """Derive gazette_type from filename. Values are renamed in 06_build_release.py for release."""
    if "(Vacancy Notices)" in filename:
        return "weekly_vacancy"
    if "(Outcome Notices)" in filename:
        return "weekly_outcome"
    if "Daily Gazette" in filename:
        return "daily"
    if "Weekly Gazette" in filename:
        return "weekly_old"
    return "unknown"


def _candidates(d: date) -> list[tuple[str, str, str]]:
    """Return (url, filename, gazette_type) candidates for a date.

    Tries PS number offsets [0, -1, 1, -2, 2] to handle edge cases
    (year boundaries, holidays) where ceil(yday/7) is off by one.
    Deduplicates by filename — a given offset may repeat a filename
    already generated by a prior offset.
    """
    date_str = d.strftime("%d %B %Y")       # "04 January 2021"
    weekday  = d.strftime("%A")             # "Monday", "Thursday", …
    is_thu   = d.weekday() == 3

    candidates: list[tuple[str, str, str]] = []
    seen: set[str] = set()

    for offset in [0, -1, 1, -2, 2]:
        n = max(1, _ps_number(d) + offset)
        ps = f"PS{n}"

        filenames: list[str] = []
        if is_thu:
            # Double-space before dash in post-2023 split format
            filenames += [
                f"{ps} Weekly Gazette Thursday (Vacancy Notices)  - {date_str}.pdf",
                f"{ps} Weekly Gazette Thursday (Outcome Notices)  - {date_str}.pdf",
                f"{ps} Weekly Gazette Thursday - {date_str}.pdf",
            ]
        filenames.append(f"{ps} Daily Gazette {weekday} - {date_str}.pdf")

        for filename in filenames:
            if filename not in seen:
                seen.add(filename)
                candidates.append((_encode(filename), filename, _gazette_type(filename)))

    return candidates

def _load_manifest() -> dict[tuple[str, str], dict]:
    """Load manifest CSV → dict keyed by (gazette_date, gazette_type)."""
    if not MANIFEST_PATH.exists():
        return {}
    entries: dict[tuple[str, str], dict] = {}
    with open(MANIFEST_PATH, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            entries[(row["gazette_date"], row["gazette_type"])] = row
    return entries


def _save_manifest(entries: dict) -> None:
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    rows = sorted(entries.values(), key=lambda r: (r["gazette_date"], r["gazette_type"]))
    with open(MANIFEST_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=MANIFEST_FIELDS)
        writer.writeheader()
        writer.writerows(rows)

def _head(url: str, session: requests.Session, timeout: int = 15) -> bool:
    try:
        r = session.head(url, timeout=timeout, allow_redirects=True)
        return r.status_code == 200
    except requests.RequestException:
        return False


def _download(url: str, dest: Path, session: requests.Session) -> bool:
    """Download url to dest with 3 retries and 5-second backoff."""
    for attempt in range(3):
        try:
            r = session.get(url, timeout=120, stream=True)
            r.raise_for_status()
            dest.parent.mkdir(parents=True, exist_ok=True)
            with open(dest, "wb") as f:
                for chunk in r.iter_content(chunk_size=65_536):
                    f.write(chunk)
            return True
        except (requests.RequestException, OSError):
            if attempt < 2:
                time.sleep(5 * (attempt + 1))
    return False

def _business_days(start: date, end: date):
    d = start
    while d <= end:
        if d.weekday() < 5:
            yield d
        d += timedelta(days=1)

def run_download(
    year_start:  int   = date.today().year,
    year_end:    int   = date.today().year,
    probe_only:  bool  = False,
    delay:       float = 2.0,
    probe_delay: float = 0.3,
    skip_probed: bool  = True,
    verbose:     bool  = False,
) -> None:

    date_start = max(date(year_start, 1, 1), EARLIEST_DATE)
    date_end   = min(date(year_end,   12, 31), date.today())

    manifest = _load_manifest()

    # Skip dates already recorded in the manifest (any status).
    probed_dates: set[str] = set()
    if skip_probed:
        probed_dates = {row["gazette_date"] for row in manifest.values()}

    print(f"Range:   {date_start} to {date_end}")
    print(f"Mode:    {'probe only (manifest not updated)' if probe_only else 'probe + download'}")
    print(f"Delays:  {delay}s download  {probe_delay}s probe")
    print()

    n_downloaded = 0
    n_skipped    = 0
    n_missing    = 0
    n_errors     = 0

    session = requests.Session()
    session.headers["User-Agent"] = "aps-gazette-pipeline/1.0 (public)"

    for d in _business_days(date_start, date_end):
        date_str = str(d)

        if date_str in probed_dates:
            continue

        candidates  = _candidates(d)
        found_any   = False
        date_entries: dict[tuple[str, str], dict] = {}

        for url, filename, gazette_type in candidates:
            if verbose:
                print(f"  probe {url}")

            exists = _head(url, session)
            time.sleep(probe_delay)

            if not exists:
                continue

            found_any = True
            key = (date_str, gazette_type)
            gazette_id = filename.split(" ")[0]   # "PS16"

            if probe_only:
                print(f"{d} | found: {filename}")
                # probe_only does not update the manifest so the date remains
                # unrecorded and will be downloaded on the next non-probe run.
                continue

            dest = PDF_DIR / filename

            if dest.exists():
                print(f"{d} | exists: {filename}")
                n_skipped += 1
                date_entries[key] = {
                    "gazette_date": date_str,
                    "gazette_id":   gazette_id,
                    "gazette_type": gazette_type,
                    "filename":     filename,
                    "url":          url,
                    "status":       "downloaded",
                }
                continue

            print(f"{d} | downloading: {filename}")
            ok = _download(url, dest, session)
            time.sleep(delay)

            if ok:
                kb = dest.stat().st_size // 1024
                print(f"     {kb} KB")
                n_downloaded += 1
                status = "downloaded"
            else:
                print(f"     ERROR")
                n_errors += 1
                status = "error"

            date_entries[key] = {
                "gazette_date": date_str,
                "gazette_id":   gazette_id,
                "gazette_type": gazette_type,
                "filename":     filename,
                "url":          url,
                "status":       status,
            }

        if not probe_only:
            if not found_any:
                # Record the date so it is skipped on future runs
                sentinel_key = (date_str, "none")
                date_entries[sentinel_key] = {
                    "gazette_date": date_str,
                    "gazette_id":   "",
                    "gazette_type": "none",
                    "filename":     "",
                    "url":          "",
                    "status":       "not_found",
                }
                n_missing += 1

            manifest.update(date_entries)
            # Save after every date — safe to interrupt and resume
            _save_manifest(manifest)

    print()
    print(f"Downloaded:  {n_downloaded}")
    print(f"Skipped:     {n_skipped}")
    print(f"Not found:   {n_missing}")
    if n_errors:
        print(f"Errors:      {n_errors}", file=sys.stderr)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Download APS PS Gazette PDFs from the public APSC S3 bucket."
    )
    parser.add_argument(
        "--year-start", type=int, default=date.today().year,
        metavar="YEAR",
        help="first year to download (default: current year)",
    )
    parser.add_argument(
        "--year-end", type=int, default=date.today().year,
        metavar="YEAR",
        help="last year to download inclusive (default: current year)",
    )
    parser.add_argument(
        "--probe-only", action="store_true",
        help="HEAD-probe only; do not download or update manifest",
    )
    parser.add_argument(
        "--delay", type=float, default=2.0, metavar="SECS",
        help="seconds to wait between downloads (default: 2.0)",
    )
    parser.add_argument(
        "--probe-delay", type=float, default=0.3, metavar="SECS",
        help="seconds to wait between HEAD probes (default: 0.3)",
    )
    parser.add_argument(
        "--no-skip", action="store_true",
        help="re-probe all dates even if already in manifest",
    )
    parser.add_argument(
        "--verbose", action="store_true",
        help="print each URL before probing",
    )
    args = parser.parse_args()

    run_download(
        year_start  = args.year_start,
        year_end    = args.year_end,
        probe_only  = args.probe_only,
        delay       = args.delay,
        probe_delay = args.probe_delay,
        skip_probed = not args.no_skip,
        verbose     = args.verbose,
    )
